### ISSUE TITLE
FFmpeg

### ISSUE THREAD

**Issue by jwmeidinger** [FoxRefire/ByeByeEXIF#2]
Hey I saw you comments on one of my questions and I'm still having problems do you mind helping me?

Here is the repo where my current code lies https://github.com/jwmeidinger/XSpacesDL

**Comment by FoxRefire** [comment]
Use ES Module
```javascript
import { FFmpeg } from "/libs/ffmpeg/ffmpeg/dist/esm/index.js"
```
https://github.com/FoxRefire/ByeByeEXIF/tree/main/libs/ffmpeg

**Comment by jvillegasd** [comment]
HI @FoxRefire! I'm sorry to reopen this issue but I kinda have similar problem, could you help me, please?

So, I'm using Webpack to create the `dist` directory I use to load the extension in my browser. I have setup Webpack in a way it gets the `esm` binaries from `node_modules` and store them in `dist` at build. You can see the directory structure in this screenshot.

<img width="282" height="527" alt="Image" src="https://github.com/user-attachments/assets/9eba3f0c-4e9d-4e02-b882-9edd6301256a" />

The problem is that I'm getting this annoying error `Cannot find module '/ffmpeg/core/ffmpeg-core.js'` when the extension runs the `offscreen` document. This is a code snippet of how I'm init the lib

```typescript
/**
 * Offscreen document for FFmpeg-based HLS audio/video merging
 */

import { MessageType } from '../shared/messages';
import { logger } from '../core/utils/logger';
import { FFmpeg } from '@ffmpeg/ffmpeg';
import { fetchFile } from '@ffmpeg/util';

// Singleton FFmpeg instance (like the competitor)
class FFmpegSingleton {
  private static instance: FFmpeg | null = null;
  private static isLoaded = false;

  static async getInstance(): Promise<FFmpeg> {
    if (!FFmpegSingleton.instance) {
      FFmpegSingleton.instance = new FFmpeg();

      await FFmpegSingleton.instance.load({
        coreURL: "/ffmpeg/core/ffmpeg-core.js",
      });

      // Set up logging
      FFmpegSingleton.instance.on('log', ({ message }) => {
        logger.debug('FFmpeg:', message);
      });

      FFmpegSingleton.isLoaded = true;
      logger.info('FFmpeg loaded successfully');
    }

    return FFmpegSingleton.instance;
  }

  static isFFmpegLoaded(): boolean {
    return FFmpegSingleton.isLoaded;
  }
}
```

**Comment by jvillegasd** [comment]
I'm using Manifest V3 and testing in Opera

```json
{  
"permissions": [
    "identity",
    "offscreen",

    "webRequest",
    "unlimitedStorage",
    "storage",
    "downloads",
    "tabs",
    "activeTab"
  ],
  "host_permissions": ["<all_urls>"],
  "background": {
    "service_worker": "background/service-worker.js",
    "type": "module"
  },
  "action": {
    "default_popup": "popup/popup.html",
    "default_icon": {
      "16": "icons/icon-16.png",
      "48": "icons/icon-48.png",
      "128": "icons/icon-128.png"
    }
  },
  "content_scripts": [
    {
      "matches": ["<all_urls>"],
      "js": ["content/content-script.js"],
      "run_at": "document_idle",
      "all_frames": true
    }
  ],
  "options_page": "options/options.html",
  "icons": {
    "16": "icons/icon-16.png",
    "48": "icons/icon-48.png",
    "128": "icons/icon-128.png"
  },
  "content_security_policy": {
    "extension_pages": "script-src 'self' 'wasm-unsafe-eval'; object-src 'self';"
  },
  "web_accessible_resources": [
    {
      "resources": [
        "ffmpeg/*"
      ],
      "matches": ["<all_urls>"]
    }
  ]
}
```

**Comment by FoxRefire** [comment]
Do you use ffmpeg.wasm in content script?
then, do that:
```diff
await FFmpegSingleton.instance.load({
--    coreURL: "/ffmpeg/core/ffmpeg-core.js",
++    coreURL: chrome.runtime.getURL("/ffmpeg/core/ffmpeg-core.js"),
});
```

**Comment by jvillegasd** [comment]
Hey man, thanks for answering! Right now I'm not using it in content script. I'm using ffmpeg only in the offscreen document. But, let me try with this change you proposed!

**Comment by FoxRefire** [comment]
Check if `/ffmpeg/core/ffmpeg-core.js` is loaded correctly in network tab of extension console

**Comment by jvillegasd** [comment]
I added the `chrome.runtime.getURL` thing and got this similar error `Error: Cannot find module 'chrome-extension://cmmdhgkoafnbmkbnbkpplildblbjlhlf/ffmpeg/core/ffmpeg-core.js'`. But now I can see the binary if I click in that link as you can see in this screenshot:

<img width="597" height="193" alt="Image" src="https://github.com/user-attachments/assets/c642a4b6-8532-4d84-aa9d-7afb2bd643bb" />

But I think you are right and the package may not be loading. I opened the network tab in the extension console as you proposed and I didn't see any call to the ffmpeg binary:

<img width="426" height="470" alt="Image" src="https://github.com/user-attachments/assets/ec8ffc4b-c96e-40e2-afe6-fe7383b2b2ac" />

**Comment by FoxRefire** [comment]
Could it be that an error occurs during the build process, but it functions correctly in the browser?

Then use `// @ts-ignore`.

**Comment by jvillegasd** [comment]
Like the extension works correctly, it just fails to load the library. I'm trying to change my approach a little bit. Like instead of using `@ffmpeg` imports, to use the binaries I'm exporting at build process. I will share my findings, thanks a lot!
